require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const http    = require('http');
const { WebSocketServer } = require('ws');
const { spawn } = require('child_process');
const path    = require('path');
const fs      = require('fs');

const PORT = 3001;
const app  = express();
app.use(cors({ origin: 'http://localhost:5173' }));
app.use(express.json());

const server = http.createServer(app);
const wss    = new WebSocketServer({ server });

// ─── Logging setup ───────────────────────────────────────────────────────────

const LOGS_DIR = path.join(__dirname, 'logs');
if (!fs.existsSync(LOGS_DIR)) fs.mkdirSync(LOGS_DIR, { recursive: true });

// One file per server session, named by start timestamp
const SESSION_TS  = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
const SESSION_LOG = path.join(LOGS_DIR, `${SESSION_TS}.txt`);

// Engines that don't have live web access — their source names are reliable
// but any URLs they produce may be hallucinated
const HALLUCINATION_ENGINES = ['claude', 'chatgpt', 'gemini'];

// Write disclaimer header once when the log file is first created
function writeLogHeader(enginesInUse) {
  const flagged = enginesInUse.filter(e => HALLUCINATION_ENGINES.includes(e));
  if (!flagged.length) return;
  const names = flagged.map(e => e.charAt(0).toUpperCase() + e.slice(1)).join(', ');
  const header = [
    '='.repeat(72),
    `Sports AI Citation Tracker — Session: ${SESSION_TS}`,
    '='.repeat(72),
    '',
    `Disclaimer: Results from ${names} are generated by language models`,
    'that do not have live web access. Source names cited are generally',
    'reliable, but any specific URLs produced by these engines may be',
    'hallucinated (correct format, fabricated article IDs). To verify a',
    "claim, search the source name + topic directly on the publisher's site.",
    '',
    'Perplexity results (when added) include real, web-searched URLs.',
    '',
    '='.repeat(72),
    '',
  ];
  fs.writeFileSync(SESSION_LOG, header.join('\n') + '\n');
}

// Ported from FE/src/lib/citationDetector.js (CommonJS)
const KNOWN_SOURCES = [
  { canonical: 'Sports Illustrated',  domain: 'si.com',                   patterns: ['sports illustrated', 'si.com'] },
  { canonical: 'ESPN',                domain: 'espn.com',                  patterns: ['espn.com', 'espn'] },
  { canonical: 'CBS Sports',          domain: 'cbssports.com',             patterns: ['cbs sports', 'cbssports.com', 'cbssports'] },
  { canonical: 'Bleacher Report',     domain: 'bleacherreport.com',        patterns: ['bleacher report', 'bleacherreport.com'] },
  { canonical: 'The Athletic',        domain: 'theathletic.com',           patterns: ['the athletic', 'theathletic.com'] },
  { canonical: 'Fox Sports',          domain: 'foxsports.com',             patterns: ['fox sports', 'foxsports.com'] },
  { canonical: 'Sky Sports',          domain: 'skysports.com',             patterns: ['sky sports', 'skysports.com'] },
  { canonical: 'BBC Sport',           domain: 'bbc.com/sport',             patterns: ['bbc sport', 'bbc.com/sport'] },
  { canonical: 'Goal.com',            domain: 'goal.com',                  patterns: ['goal.com'] },
  { canonical: '247Sports',           domain: '247sports.com',             patterns: ['247sports.com', '247sports'] },
  { canonical: 'NBA.com',             domain: 'nba.com',                   patterns: ['nba.com'] },
  { canonical: 'NFL.com',             domain: 'nfl.com',                   patterns: ['nfl.com'] },
  { canonical: 'MLB.com',             domain: 'mlb.com',                   patterns: ['mlb.com'] },
  { canonical: 'Reuters',             domain: 'reuters.com',               patterns: ['reuters.com', 'reuters'] },
  { canonical: 'AP News',             domain: 'apnews.com',                patterns: ['apnews.com', 'associated press', 'ap news'] },
  { canonical: 'Yahoo Sports',        domain: 'sports.yahoo.com',          patterns: ['sports.yahoo.com', 'yahoo sports'] },
  { canonical: 'Sporting News',       domain: 'sportingnews.com',          patterns: ['sportingnews.com', 'sporting news'] },
  { canonical: 'NBC Sports',          domain: 'nbcsports.com',             patterns: ['nbcsports.com', 'nbc sports'] },
  { canonical: 'FanSided',            domain: 'fansided.com',              patterns: ['fansided.com', 'fansided'] },
  { canonical: '90min',               domain: '90min.com',                 patterns: ['90min.com', '90min'] },
  { canonical: 'Marca',               domain: 'marca.com',                 patterns: ['marca.com', ' marca'] },
  { canonical: 'ProFootballReference',domain: 'pro-football-reference.com',patterns: ['pro-football-reference', 'pro football reference'] },
  { canonical: 'Basketball Reference',domain: 'basketball-reference.com',  patterns: ['basketball-reference', 'basketball reference'] },
  { canonical: 'UFC.com',             domain: 'ufc.com',                   patterns: ['ufc.com', 'ufc'] },
  { canonical: 'NHL.com',             domain: 'nhl.com',                   patterns: ['nhl.com'] },
  { canonical: 'Transfermarkt',       domain: 'transfermarkt.com',         patterns: ['transfermarkt'] },
  { canonical: 'WhoScored',           domain: 'whoscored.com',             patterns: ['whoscored'] },
  { canonical: 'Wikipedia',           domain: 'wikipedia.org',             patterns: ['wikipedia.org', 'wikipedia'] },
  { canonical: 'NCAA.org',            domain: 'ncaa.org',                  patterns: ['ncaa.org', 'ncaa'] },
];

/**
 * Extracts source names from the "Sources:" block the AI returns.
 * Does NOT generate or trust LLM-provided URLs (they hallucinate).
 * If any real URLs slip through we validate them via HTTP HEAD.
 */
function extractSources(text) {
  const results = [];
  const seenNames = new Set();

  // ── Parse the structured Sources section ──────────────────────────────────
  const sectionMatch = text.match(/(?:^|\n)(?:#+\s*)?sources?:?\s*\n([\s\S]*?)(?=\n(?:#+\s*)\S|$)/i);
  const block = sectionMatch ? sectionMatch[1] : text;

  // Match lines like: "1. ESPN" or "- Basketball Reference" or "* NBA.com"
  // Also handles "1. ESPN: https://..." — we keep the name, drop the URL
  const lineRe = /^[\s\-*\d.)]*([A-Za-z0-9][^\n:]{2,60})(?::.*)?$/gm;
  let m;
  while ((m = lineRe.exec(block)) !== null) {
    const name = m[1].trim().replace(/\*+/g, '').replace(/\.$/, '');
    if (!name || seenNames.has(name.toLowerCase())) continue;

    // Skip lines that are clearly prose, not source names
    if (name.split(' ').length > 6) continue;

    seenNames.add(name.toLowerCase());
    results.push({ name });
  }

  // ── Also match via KNOWN_SOURCES patterns for reliability ─────────────────
  const lower = text.toLowerCase();
  KNOWN_SOURCES.forEach(src => {
    if (seenNames.has(src.canonical.toLowerCase())) return;
    if (src.patterns.some(p => lower.includes(p.toLowerCase()))) {
      seenNames.add(src.canonical.toLowerCase());
      results.push({ name: src.canonical });
    }
  });

  return results;
}

/**
 * Validates URLs that slip through by making a HEAD request.
 * Returns { url, status: 'ok' | 'broken' | 'error', code }
 */
async function validateUrl(url) {
  try {
    const res = await fetch(url, { method: 'HEAD', signal: AbortSignal.timeout(6000),
      headers: { 'User-Agent': 'Mozilla/5.0' } });
    return { url, status: res.ok ? 'ok' : 'broken', code: res.status };
  } catch {
    return { url, status: 'error', code: null };
  }
}

function writeLog(promptIdx, promptText, ai, text) {
  const sources = extractSources(text);
  const lines   = [
    `prompt ${promptIdx + 1} [${promptText.slice(0, 80)}${promptText.length > 80 ? '…' : ''}], ${ai} results:`,
  ];

  if (sources.length === 0) {
    lines.push('  (no sources detected)');
  } else {
    sources.forEach(({ name }) => lines.push(`  - ${name}`));
  }
  lines.push('');

  fs.appendFileSync(SESSION_LOG, lines.join('\n') + '\n');
  console.log(`[LOG] wrote ${sources.length} source(s) for prompt ${promptIdx + 1} / ${ai}`);
}

// ─── WebSocket ───────────────────────────────────────────────────────────────

function broadcast(msg) {
  const data = JSON.stringify(msg);
  wss.clients.forEach(client => {
    if (client.readyState === 1) client.send(data);
  });
}

wss.on('connection', ws => {
  console.log('[WS] client connected');
  ws.on('close', () => console.log('[WS] client disconnected'));
});

// ─── Routes ──────────────────────────────────────────────────────────────────

let activeRunner = null;

// POST /api/auth — validates the magic password
app.post('/api/auth', (req, res) => {
  const { password } = req.body;
  const magic = process.env.MAGIC_PASSWORD;
  if (!magic) return res.status(500).json({ ok: false, error: 'MAGIC_PASSWORD not set in .env' });
  if (password === magic) return res.json({ ok: true });
  return res.status(401).json({ ok: false, error: 'Invalid password' });
});

// POST /api/run-prompt
app.post('/api/run-prompt', (req, res) => {
  const { promptIdx, promptText, engines, keys } = req.body;
  if (promptIdx === undefined || !promptText) {
    return res.status(400).json({ ok: false, error: 'Missing promptIdx or promptText' });
  }
  if (activeRunner) {
    return res.status(409).json({ ok: false, error: 'A run is already in progress' });
  }

  const engineList = Array.isArray(engines) && engines.length ? engines : null;
  console.log(`[BE] Running prompt ${promptIdx} [${engineList ? engineList.join(',') : 'all'}]: "${promptText.slice(0, 60)}..."`);

  // Write disclaimer header once per session on the first run
  if (!fs.existsSync(SESSION_LOG)) {
    writeLogHeader(['claude', 'chatgpt', 'gemini']);
  }

  const envExtra = { PROMPT_IDX: String(promptIdx), PROMPT_TEXT: promptText };
  if (engineList) envExtra.ENGINES = engineList.join(',');
  // Allow user-supplied API keys to override .env values
  if (keys) {
    if (keys.anthropic) envExtra.ANTHROPIC_API_KEY = keys.anthropic;
    if (keys.gemini)    envExtra.GEMINI_API_KEY    = keys.gemini;
    if (keys.tavily)    envExtra.TAVILY_API_KEY     = keys.tavily;
    if (keys.github)    envExtra.GITHUB_TOKEN       = keys.github;
  }

  const runner = spawn('node', [path.join(__dirname, 'runner.js')], {
    env:   { ...process.env, ...envExtra },
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  activeRunner = runner;

  runner.stdout.on('data', chunk => {
    chunk.toString().split('\n').forEach(line => {
      line = line.trim();
      if (!line) return;
      if (line.startsWith('[MSG]')) {
        try {
          const msg = JSON.parse(line.slice(5).trim());
          // Hook: write log when a response comes in
          if (msg.type === 'response') {
            writeLog(msg.promptIdx, promptText, msg.ai, msg.text);
          }
          broadcast(msg);
        } catch (e) {
          console.error('[BE] bad MSG line:', line);
        }
      } else {
        console.log('[runner]', line);
      }
    });
  });

  runner.stderr.on('data', chunk => {
    console.error('[runner stderr]', chunk.toString().trim());
  });

  runner.on('close', code => {
    console.log(`[BE] runner exited with code ${code}`);
    activeRunner = null;
    broadcast({ type: 'done' });
  });

  res.json({ ok: true });
});

// GET /api/status
app.get('/api/status', (req, res) => {
  res.json({ running: !!activeRunner });
});

// POST /api/stop
app.post('/api/stop', (req, res) => {
  if (activeRunner) {
    activeRunner.kill();
    activeRunner = null;
    broadcast({ type: 'stopped' });
  }
  res.json({ ok: true });
});

server.listen(PORT, () => {
  console.log(`[BE] ready on :${PORT}`);
  console.log(`[LOG] session log: ${SESSION_LOG}`);
});
